# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '班级'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师'},
        ),
    ]
