# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '角色控制',
                'verbose_name_plural': '角色控制',
            },
        ),
        migrations.CreateModel(
            name='UserPurview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=80)),
                ('is_menu', models.BooleanField(default=False, verbose_name='菜单')),
                ('icon', models.CharField(blank=True, max_length=24, null=True, verbose_name='图标')),
            ],
            options={
                'verbose_name': '权限控制',
                'verbose_name_plural': '权限控制',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rbac.UserPurview'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
